name: Sync to upstream

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  fetch-upstream:
    name: Fetch Upstream
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          ref: master
      - name: Configure Git
        run: |
          git config --global user.email "dev-team@redis.com"
          git config --global user.name "Dev team"
          git remote add upstream https://github.com/disposable/disposable-email-domains.git
      - name: Fetch and merge
        run: |
          git fetch upstream
          git checkout master
          git merge upstream/master -X theirs --allow-unrelated-histories          
          git push origin master