name: Sync to upstream

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  fetch-upstream:
    name: Fetch Upstream
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config --global user.email "test1@dredis.com"
          git config --global user.name "Test Build"
          git remote add upstream https://github.com/disposable/disposable-email-domains.git
      - name: Fetch and merge
        run: |
          git fetch upstream
          git merge upstream/master --allow-unrelated-histories          
          git push origin master